import http from 'node:http';
import {URL} from 'node:url';
import {loadDb,getLibrary,addFavorite,removeFavorite,addHistory} from './db.js';
import * as providers from './providers.js';
const PORT=Number(process.env.PORT||8787),HOST=process.env.HOST||'127.0.0.1',origin=process.env.CORS_ORIGIN||'*';
function send(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type'});res.end(JSON.stringify(data));}
async function body(req){let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{};}
const parts=p=>p.split('/').filter(Boolean);
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type'});return res.end();}const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{await loadDb();if(u.pathname==='/health')return send(res,200,{ok:true,service:'kurd-anime-api',version:'0.3.0',time:new Date().toISOString()});if(u.pathname==='/api/config')return send(res,200,{appName:'Kurd Anime',version:'0.3.0',languages:['ku','en','ar'],defaultLanguage:'ku',features:{metadata:true,library:true,history:true,streamingProviders:true}});const p=parts(u.pathname);if(p[0]!=='api')return send(res,404,{error:'Not found'});if(p[1]==='anime'&&p[2]==='trending'&&req.method==='GET')return send(res,200,{data:await providers.trending()});if(p[1]==='anime'&&p[2]==='search'&&req.method==='GET')return send(res,200,{data:await providers.search(u.searchParams.get('q')||'')});if(p[1]==='anime'&&p[2]&&p[3]==='episodes'&&req.method==='GET')return send(res,200,{data:await providers.episodes(p[2])});if(p[1]==='anime'&&p[2]&&req.method==='GET')return send(res,200,{data:await providers.detail(p[2])});if(p[1]==='library'&&p[2]){const user=p[2];if(req.method==='GET')return send(res,200,{data:await getLibrary(user)});if(req.method==='POST'&&p[3]==='favorites')return send(res,200,{data:await addFavorite(user,await body(req))});if(req.method==='DELETE'&&p[3]==='favorites'&&p[4])return send(res,200,{data:await removeFavorite(user,p[4])});if(req.method==='POST'&&p[3]==='history')return send(res,200,{data:await addHistory(user,await body(req))});}return send(res,404,{error:'Route not found'});}catch(e){console.error(e);return send(res,502,{error:e.message||'Upstream error'});}}).listen(PORT,HOST,()=>console.log(`Kurd Anime API listening on http://${HOST}:${PORT}`));
