import { useMemo } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { animeCatalog } from "@/lib/catalog";

export default function AnimeDetailsScreen() {
  const colors = useColors();
  const { id } = useLocalSearchParams<{ id: string }>();
  const anime = useMemo(() => animeCatalog.find((item) => item.id === id) ?? animeCatalog[0], [id]);
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}>
    <Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color={colors.foreground} /><Text style={[styles.backText, { color: colors.foreground }]}>گەڕانەوە</Text></Pressable>
    <View style={styles.hero}><Image source={{ uri: anime.cover }} style={styles.cover} /><View style={styles.heroText}><Text style={[styles.title, { color: colors.foreground }]}>{anime.title}</Text><Text style={[styles.meta, { color: colors.muted }]}>{anime.subtitle} · {anime.genre}</Text><View style={styles.rating}><IconSymbol name="star.fill" size={15} color="#FBBF24" /><Text style={[styles.ratingText, { color: colors.foreground }]}>{anime.rating} نمرە</Text></View><Pressable style={({ pressed }) => [styles.play, { backgroundColor: colors.primary }, pressed && { opacity: .8 }]} onPress={() => router.push({ pathname: "/player/[id]", params: { id: anime.id, episode: "1" } })}><IconSymbol name="play.fill" size={16} color="#fff" /><Text style={styles.playText}>یەکەم ئەڵقە ببینە</Text></Pressable></View></View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>دەربارەی</Text><Text style={[styles.synopsis, { color: colors.muted }]}>{anime.synopsis}</Text>
    <View style={styles.sectionRow}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>ئەڵقەکان</Text><Text style={[styles.count, { color: colors.primary }]}>{anime.episodes} ئەڵقە</Text></View>
    {anime.episodesList.map((episode) => <Pressable key={episode.number} style={({ pressed }) => [styles.episode, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: .75 }]} onPress={() => router.push({ pathname: "/player/[id]", params: { id: anime.id, episode: String(episode.number) } })}><View style={[styles.number, { backgroundColor: colors.primary }]}><Text style={styles.numberText}>{episode.number}</Text></View><View style={styles.epInfo}><Text style={[styles.epTitle, { color: colors.foreground }]}>{episode.title}</Text><Text style={[styles.epMeta, { color: colors.muted }]}>{episode.duration} · زیرنووس</Text></View><IconSymbol name="play.fill" size={16} color={colors.primary} /></Pressable>)}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 36 }, back: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 20 }, backText: { fontSize: 13, fontWeight: "700" }, hero: { flexDirection: "row", gap: 16, marginBottom: 24 }, cover: { width: 128, height: 185, borderRadius: 16, backgroundColor: "#20253D" }, heroText: { flex: 1, justifyContent: "center" }, title: { fontSize: 24, lineHeight: 29, fontWeight: "900" }, meta: { marginTop: 7, fontSize: 12 }, rating: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 12 }, ratingText: { fontSize: 12, fontWeight: "700" }, play: { borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, flexDirection: "row", gap: 6, alignItems: "center", alignSelf: "flex-start", marginTop: 15 }, playText: { color: "#fff", fontWeight: "800", fontSize: 12 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginBottom: 9 }, synopsis: { fontSize: 13, lineHeight: 22, marginBottom: 24 }, sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }, count: { fontSize: 12, fontWeight: "800" }, episode: { minHeight: 64, borderRadius: 15, borderWidth: 1, flexDirection: "row", alignItems: "center", padding: 10, marginBottom: 9 }, number: { width: 40, height: 40, borderRadius: 12, justifyContent: "center", alignItems: "center" }, numberText: { color: "#fff", fontWeight: "900" }, epInfo: { flex: 1, marginLeft: 12 }, epTitle: { fontSize: 14, fontWeight: "800" }, epMeta: { fontSize: 11, marginTop: 4 } });
