import { useMemo, useState } from "react";
import { FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { animeCatalog, type Anime } from "@/lib/catalog";

const genres = ["هەموو", "ئاکشن", "فانتەزی", "کۆمیدی", "دراما"];
export default function HomeScreen() {
  const colors = useColors(); const [query, setQuery] = useState(""); const [genre, setGenre] = useState("هەموو");
  const filtered = useMemo(() => animeCatalog.filter((item: Anime) => `${item.title} ${item.subtitle}`.toLowerCase().includes(query.toLowerCase()) && (genre === "هەموو" || item.genre === genre)), [genre, query]);
  const renderCard = ({ item }: { item: Anime }) => <Pressable style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]} onPress={() => router.push({ pathname: "/anime/[id]" as never, params: { id: item.id } })}><Image source={{ uri: item.cover }} style={styles.cover} /><View style={styles.cardBody}><Text numberOfLines={1} style={[styles.cardTitle, { color: colors.foreground }]}>{item.title}</Text><Text numberOfLines={1} style={[styles.cardMeta, { color: colors.muted }]}>{item.subtitle}</Text><View style={styles.cardFooter}><Text style={[styles.episode, { color: colors.primary }]}>{item.episodes} ئەڵقە</Text><View style={styles.rating}><IconSymbol name="star.fill" size={13} color="#FBBF24" /><Text style={[styles.ratingText, { color: colors.muted }]}>{item.rating}</Text></View></View></View></Pressable>;
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={filtered} keyExtractor={(item) => item.id} numColumns={2} renderItem={renderCard} columnWrapperStyle={styles.grid} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>KURD ANIME</Text><Text style={[styles.heading, { color: colors.foreground }]}>ئەنیمەکەت، لەوێیە</Text></View><Image source={require("../../assets/images/kurd-anime-icon.png")} style={styles.logo} /></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="magnifyingglass" size={20} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="گەڕان بۆ ئەنیمە..." placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View><View style={styles.hero}><Image source={{ uri: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80" }} style={styles.heroImage} /><View style={styles.heroShade} /><View style={styles.heroCopy}><Text style={styles.heroKicker}>نوێ و بەهێز</Text><Text style={styles.heroTitle}>Jujutsu Kaisen</Text><Text style={styles.heroSub}>ئێستا ببینە · زیرنووسی کوردی بە زودی</Text><Pressable style={({ pressed }) => [styles.heroButton, pressed && styles.pressed]} onPress={() => router.push({ pathname: "/anime/[id]" as never, params: { id: "jujutsu" } })}><IconSymbol name="play.fill" size={16} color="#0B1020" /><Text style={styles.heroButtonText}>بینین</Text></Pressable></View></View><View style={styles.sectionRow}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>پێشنیارکراو بۆ تۆ</Text><Text style={[styles.sectionLink, { color: colors.primary }]}>{filtered.length} دانە</Text></View><View style={styles.chips}>{genres.map((item) => <Pressable key={item} onPress={() => setGenre(item)} style={[styles.chip, { backgroundColor: genre === item ? colors.primary : colors.surface, borderColor: genre === item ? colors.primary : colors.border }]}><Text style={[styles.chipText, { color: genre === item ? "#fff" : colors.muted }]}>{item}</Text></Pressable>)}</View></>} ListEmptyComponent={<View style={styles.empty}><Text style={[styles.emptyTitle, { color: colors.foreground }]}>هیچ ئەنجامێک نەدۆزرایەوە</Text><Text style={[styles.emptyText, { color: colors.muted }]}>وشەیەکی تر تاقی بکەرەوە</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 28 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, eyebrow: { fontSize: 12, letterSpacing: 2, fontWeight: "800" }, heading: { fontSize: 26, fontWeight: "800", marginTop: 5 }, logo: { width: 58, height: 58, borderRadius: 18 }, search: { borderRadius: 14, borderWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, height: 50, marginBottom: 18 }, input: { flex: 1, marginLeft: 10, textAlign: "right", fontSize: 14 }, hero: { height: 178, borderRadius: 22, overflow: "hidden", marginBottom: 24 }, heroImage: { width: "100%", height: "100%" }, heroShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(5,10,29,.58)" }, heroCopy: { position: "absolute", left: 18, bottom: 17 }, heroKicker: { color: "#FF3148", fontSize: 11, fontWeight: "800", marginBottom: 4 }, heroTitle: { color: "#fff", fontSize: 24, fontWeight: "800" }, heroSub: { color: "#D6DAEA", fontSize: 11, marginTop: 3 }, heroButton: { marginTop: 11, alignSelf: "flex-start", backgroundColor: "#fff", borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 6 }, heroButtonText: { color: "#0B1020", fontWeight: "800", fontSize: 12 }, sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }, sectionTitle: { fontSize: 18, fontWeight: "800" }, sectionLink: { fontSize: 12, fontWeight: "700" }, chips: { flexDirection: "row", gap: 8, marginBottom: 18 }, chip: { borderRadius: 20, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 7 }, chipText: { fontSize: 12, fontWeight: "700" }, grid: { gap: 12, marginBottom: 12 }, card: { flex: 1, maxWidth: "50%", borderRadius: 16, overflow: "hidden", borderWidth: 1 }, cover: { width: "100%", aspectRatio: .72, backgroundColor: "#20253D" }, cardBody: { padding: 10 }, cardTitle: { fontSize: 14, fontWeight: "800" }, cardMeta: { fontSize: 11, marginTop: 4 }, cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 9 }, episode: { fontSize: 10, fontWeight: "800" }, rating: { flexDirection: "row", alignItems: "center", gap: 3 }, ratingText: { fontSize: 10 }, pressed: { opacity: .78, transform: [{ scale: .985 }] }, empty: { alignItems: "center", padding: 40 }, emptyTitle: { fontWeight: "800", fontSize: 16 }, emptyText: { marginTop: 6, fontSize: 13 } });
