const DEFAULT_API='https://kurd-anime-rho.vercel.app/api';
const qs=new URLSearchParams(location.search);
let API=qs.get('api')||localStorage.getItem('apiBase')||DEFAULT_API;
let lang=localStorage.lang||'ku', page='home', lastQuery='';
const makeId=()=>{try{if(crypto.randomUUID)return crypto.randomUUID()}catch(e){}return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)};
const DEVICE_ID=localStorage.deviceId||(localStorage.deviceId='android-'+makeId());
const T={
 ku:{home:'ماڵەوە',anime:'ئەنیمەکان',movies:'فیلم و زنجیرە',library:'کتێبخانە',more:'زیاتر',trending:'بەناوبانگ',latest:'نوێترین',popular:'زۆر بینراو',search:'گەڕان',settings:'ڕێکخستنەکان',watch:'بینین',favorite:'دڵخواز',favorites:'دڵخوازەکان',remove:'لابردن',add:'زیادکردن',language:'زمان',query:'ناوی ئەنیمە بگەڕێ...',server:'بەستەری سێرڤەر',save:'پاشەکەوتکردن',loading:'چاوەڕوان بە...',retry:'دووبارە هەوڵبدەرەوە',offline:'پەیوەندی بە سێرڤەرەکە نییە.',noResults:'هیچ ئەنجامێک نەدۆزرایەوە',genres:'جۆرەکان',year:'ساڵ',type:'جۆر',status:'دۆخ',episodes:'ئەڵقەکان',continue:'بەردەوام بە بینین',empty:'هێشتا هیچ شتێک نییە',serverPick:'سێرڤەر هەڵبژێرە',back:'گەڕانەوە',playing:'لە بینینە',error:'هەڵە ڕوویدا',movie:'فیلم',tv:'زنجیرە'},
 en:{home:'Home',anime:'Anime',movies:'Movies & TV',library:'Library',more:'More',trending:'Trending',latest:'Latest',popular:'Popular',search:'Search',settings:'Settings',watch:'Watch',favorite:'Favorite',favorites:'Favorites',remove:'Remove',add:'Add',language:'Language',query:'Search anime...',server:'Server URL',save:'Save',loading:'Loading...',retry:'Retry',offline:'Server is not reachable.',noResults:'No results found',genres:'Genres',year:'Year',type:'Type',status:'Status',episodes:'Episodes',continue:'Continue watching',empty:'Nothing here yet',serverPick:'Choose a server',back:'Back',playing:'Now playing',error:'Something went wrong',movie:'Movie',tv:'TV'},
 ar:{home:'الرئيسية',anime:'الأنمي',movies:'الأفلام والمسلسلات',library:'المكتبة',more:'المزيد',trending:'الأكثر رواجاً',latest:'الأحدث',popular:'الأكثر مشاهدة',search:'بحث',settings:'الإعدادات',watch:'مشاهدة',favorite:'المفضلة',favorites:'المفضلات',remove:'إزالة',add:'إضافة',language:'اللغة',query:'ابحث عن أنمي...',server:'رابط الخادم',save:'حفظ',loading:'جار التحميل...',retry:'إعادة المحاولة',offline:'لا يمكن الوصول إلى الخادم.',noResults:'لم يتم العثور على نتائج',genres:'التصنيفات',year:'السنة',type:'النوع',status:'الحالة',episodes:'الحلقات',continue:'متابعة المشاهدة',empty:'لا يوجد شيء بعد',serverPick:'اختر الخادم',back:'رجوع',playing:'يتم التشغيل',error:'حدث خطأ',movie:'فيلم',tv:'مسلسل'}};
const t=k=>T[lang]?.[k]||T.en[k]||k;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function clean(s){return String(s??'').replace(/<[^>]*>/g,'').trim()}
function arr(j){if(Array.isArray(j))return j;if(Array.isArray(j?.data))return j.data;if(Array.isArray(j?.data?.results))return j.data.results;if(Array.isArray(j?.results))return j.results;if(Array.isArray(j?.data?.animes))return j.data.animes;if(Array.isArray(j?.animes))return j.animes;return []}
function one(j){return j?.data?.anime||j?.data?.info||j?.data||j?.anime||j}
function norm(x){if(!x)return null;return {id:x.id||x.anime_id||x.slug||x.url,title:x.title||x.name||x.english||x.romaji||'Untitled',poster:x.poster||x.img||x.image||x.coverImage?.large||x.cover||x.thumbnail||'',banner:x.banner||x.cover||x.coverImage?.extraLarge||x.img||'',score:x.score??x.averageScore??x.rating??null,year:x.year||x.releasedYear||x.releaseDate||x.aired_in||'',description:x.description||x.descriptions||x.synopsis||'',genres:x.genres||x.genre||[],type:x.type||x.format||'',status:x.status||'',episodes:x.totalEpisodes||x.episodes?.eps||x.episodes||null,raw:x}}
function normalizeList(j){return arr(j).map(norm).filter(x=>x?.id)}
async function api(path,opt={}){if(!API)throw Error('API_NOT_CONFIGURED');const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(API.replace(/\/$/,'')+path,{...opt,signal:c.signal,headers:{accept:'application/json','x-device-id':DEVICE_ID,...(opt.headers||{})}});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){if(e.name==='AbortError')throw Error('TIMEOUT');throw e}finally{clearTimeout(timer)}}
async function first(paths){let last;for(const p of paths){try{return await api(p)}catch(e){last=e}}throw last||Error('NO_ENDPOINT')}
function getFav(){try{return JSON.parse(localStorage.favorites||'[]')}catch{return[]}}
function setFav(a){localStorage.favorites=JSON.stringify(a)}
function isFav(id){return getFav().some(x=>x.id===id)}
function toggleFav(x){const a=getFav(),i=a.findIndex(v=>v.id===x.id);if(i>=0)a.splice(i,1);else a.unshift(x);setFav(a);return i<0}
function getProgress(){try{return JSON.parse(localStorage.progress||'{}')}catch{return{}}}
function saveProgress(id,episode,time,duration,title,poster){const p=getProgress();p[id]={id,episode,time,duration,title,poster,updated:Date.now()};localStorage.progress=JSON.stringify(p)}
function removeProgress(id){const p=getProgress();delete p[id];localStorage.progress=JSON.stringify(p)}
function top(){return `<header class="top"><button class="icon-btn" onclick="go('home')">☰</button><div class="brand">KURD<span>ANIME</span></div><button class="icon-btn" onclick="searchPage()">⌕</button></header>`}
function nav(){return `<nav class="bottom">${[['home','⌂'],['anime','◉'],['movies','▣'],['library','♡'],['more','☷']].map(x=>`<button class="nav ${page===x[0]?'active':''}" onclick="go('${x[0]}')"><i>${x[1]}</i><small>${t(x[0])}</small></button>`).join('')}</nav>`}
function state(msg,retry=true){return `<div class="state"><div class="state-icon">!</div><b>${esc(msg)}</b>${retry?'<button class="cta" onclick="render()">'+t('retry')+'</button>':''}</div>`}
function card(x){const fav=isFav(x.id);return `<article class="card" onclick="detail('${esc(x.id)}')"><div class="poster">${x.poster?`<img src="${esc(x.poster)}" loading="lazy" alt="">`:'<span>KA</span>'}<button class="heart ${fav?'on':''}" onclick="event.stopPropagation();quickFav('${esc(x.id)}')">${fav?'♥':'♡'}</button>${x.score!=null?`<em>⭐ ${esc(x.score)}</em>`:''}</div><b>${esc(x.title)}</b><small>${esc(x.year||x.type||'')}</small></article>`}
function grid(items){return items.length?`<div class="grid">${items.map(card).join('')}</div>`:`<div class="empty">${t('noResults')}</div>`}
function quickFav(id){const all=[...getFav()];const x=all.find(v=>v.id===id);if(x)toggleFav(x);else{const raw=window._items?.find(v=>v.id===id);if(raw)toggleFav(raw)}render()}
function section(title,items,more=''){return `<section class="section"><div class="section-head"><h2>${title}</h2>${more}</div>${grid(items)}</section>`}
async function home(){let trending=[],latest=[],popular=[];try{const [a,b,c]=await Promise.all([first(['/anime/trending','/trending']),first(['/anime/recent','/anime/latest','/recent']).catch(()=>({})),first(['/anime/popular','/popular']).catch(()=>({}))]);trending=normalizeList(a);latest=normalizeList(b);popular=normalizeList(c)}catch(e){if(!trending.length)throw e}window._items=[...trending,...latest,...popular];const cont=Object.values(getProgress()).sort((a,b)=>b.updated-a.updated).slice(0,5);return `${top()}<section class="hero"><div class="glow"></div><span class="pill">KURD ANIME</span><h1>باشترین ئەنیمەکان لە یەک ئەپدا</h1><p>بگەڕێ، دۆزیوە، دڵخوازەکانت هەڵبگرە و بینینەکەت بەردەوام بکە.</p><button class="cta" onclick="go('anime')">${t('anime')} ↗</button></section>${cont.length?`<section class="section"><div class="section-head"><h2>${t('continue')}</h2></div><div class="continue">${cont.map(x=>`<div class="cont" onclick="detail('${esc(x.id)}')"><img src="${esc(x.poster||'')}" alt=""><div><b>${esc(x.title)}</b><small>Episode ${esc(x.episode||'-')} • ${Math.round((x.time||0)/60)}m</small><div class="bar"><i style="width:${x.duration?Math.min(100,(x.time/x.duration)*100):0}%"></i></div></div></div>`).join('')}</div></section>`:''}${trending.length?section(t('trending'),trending.slice(0,10)):''}${latest.length?section(t('latest'),latest.slice(0,10)):''}${popular.length?section(t('popular'),popular.slice(0,10)):''}${nav()}`}
async function anime(){let items=[];try{items=normalizeList(await first(['/anime/trending','/trending']))}catch(e){}window._items=items;return `${top()}<section class="section search-wrap"><input id="q" class="search" value="${esc(lastQuery)}" placeholder="${t('query')}" oninput="suggest(this.value)" onkeydown="if(event.key==='Enter')search(this.value)"><div id="suggest"></div></section><section class="section"><div class="chips"><button onclick="loadCategory('popular')">${t('popular')}</button><button onclick="loadCategory('movie')">${t('movie')}</button><button onclick="loadCategory('tv')">${t('tv')}</button></div>${items.length?grid(items):state(t('offline'),false)}</section>${nav()}`}
async function loadCategory(type){page='anime';try{let j=await first(type==='popular'?['/anime/popular','/popular']:type==='movie'?['/anime/movies','/movies','/anime/filter?format=MOVIE']:['/anime/tv','/anime/filter?format=TV']);window._items=normalizeList(j);document.getElementById('app').innerHTML=top()+`<section class="section"><h2>${t(type==='popular'?'popular':type==='movie'?'movie':'tv')}</h2>${grid(window._items)}</section>`+nav()}catch(e){document.getElementById('app').innerHTML=top()+state(t('offline'))+nav()}}
async function search(q){lastQuery=String(q||'').trim();if(!lastQuery)return render();let items=[];try{items=normalizeList(await first(['/anime/search?q='+encodeURIComponent(lastQuery),'/search?q='+encodeURIComponent(lastQuery),'/anime/search?query='+encodeURIComponent(lastQuery)]))}catch(e){}window._items=items;document.getElementById('app').innerHTML=top()+`<section class="section search-wrap"><input class="search" autofocus value="${esc(lastQuery)}" placeholder="${t('query')}" onkeydown="if(event.key==='Enter')search(this.value)"></section><section class="section"><h2>${t('search')}: ${esc(lastQuery)}</h2>${grid(items)}</section>`+nav()}
function searchPage(){page='anime';render()}
function suggest(q){const box=document.getElementById('suggest');if(!box)return;if(q.length<2){box.innerHTML='';return}box.innerHTML=`<button class="suggest" onclick="search(document.getElementById('q').value)">⌕ ${esc(q)}</button>`}
async function detail(id){page='anime';document.getElementById('app').innerHTML=top()+`<div class="loading">${t('loading')}</div>`+nav();try{const j=await first(['/anime/'+encodeURIComponent(id),'/anime/anilist/'+encodeURIComponent(id)]);const x=norm(one(j));if(!x)throw Error('NOT_FOUND');window.current=x;let episodes=[];const d=one(j);if(Array.isArray(d?.episodes))episodes=d.episodes;else if(Array.isArray(d?.data?.episodes))episodes=d.data.episodes;const fav=isFav(x.id);document.getElementById('app').innerHTML=top()+`<section class="detail-hero" style="--bg:url('${esc(x.banner||x.poster)}')"><div class="detail-bg"></div><div class="detail-info"><img src="${esc(x.poster||'')}" alt=""><div><h1>${esc(x.title)}</h1><p>${x.year||''}${x.score!=null?' • ⭐ '+esc(x.score):''}</p><div class="chips">${(Array.isArray(x.genres)?x.genres:[]).slice(0,5).map(g=>`<span>${esc(g)}</span>`).join('')}</div></div></div></section><section class="section detail-body"><div class="actions"><button class="cta" onclick="episodes('${esc(x.id)}')">▶ ${t('watch')}</button><button class="outline" onclick="toggleDetailFav()">${fav?'♥ '+t('remove'):'♡ '+t('favorite')}</button></div><p class="desc">${esc(clean(x.description)||'')}</p><div class="meta"><span>${t('type')}<b>${esc(x.type||'-')}</b></span><span>${t('status')}<b>${esc(x.status||'-')}</b></span><span>${t('episodes')}<b>${esc(x.episodes||episodes.length||'-')}</b></span></div>${episodes.length?`<h2>${t('episodes')}</h2><div class="eps">${episodes.map(e=>episodeButton(x,e)).join('')}</div>`:''}</section>`+nav()}catch(e){document.getElementById('app').innerHTML=top()+state(t('error')+' • '+(e.message||''))+nav()}}
function toggleDetailFav(){if(window.current){toggleFav(window.current);detail(window.current.id)}}
function episodeButton(anime,e){const n=e.number??e.episodeNumber??e.ep??e.id;const id=e.id||e.episodeId||n;return `<button class="ep" onclick="playEpisode('${esc(anime.id)}','${esc(id)}','${esc(n)}','${esc(e.url||'')}','${esc(anime.title)}','${esc(anime.poster)}')"><span>${esc(e.title||'Episode '+n)}</span><small>${esc(n)}</small></button>`}
async function episodes(id){try{const j=await first(['/anime/'+encodeURIComponent(id)+'/episodes','/episodes/'+encodeURIComponent(id),'/anime/'+encodeURIComponent(id)]);const d=one(j),eps=Array.isArray(d?.episodes)?d.episodes:(Array.isArray(j?.data?.episodes)?j.data.episodes:[]);const x=window.current||norm(d);document.getElementById('app').innerHTML=top()+`<section class="section"><button class="back" onclick="detail('${esc(id)}')">← ${t('back')}</button><h2>${t('episodes')}</h2>${eps.length?`<div class="eps">${eps.map(e=>episodeButton(x,e)).join('')}</div>`:state(t('noResults'),false)}</section>`+nav()}catch(e){detail(id)}}
async function playEpisode(animeId,episodeId,number,url,title,poster){if(url){openPlayer(url,title,poster,animeId,number);return}try{const j=await first(['/anime/'+encodeURIComponent(animeId)+'/episodes/'+encodeURIComponent(episodeId),'/episodes/'+encodeURIComponent(episodeId),'/anime/'+encodeURIComponent(animeId)+'/episode/'+encodeURIComponent(episodeId)]);const d=one(j),sources=d?.sources||j?.sources||d?.servers||j?.servers||[];if(!sources.length)throw Error('NO_STREAM');if(sources.length===1){openPlayer(sources[0].url||sources[0].src,title,poster,animeId,number);return}showServers(sources,title,poster,animeId,number)}catch(e){document.getElementById('app').innerHTML=top()+state(t('error')+' • '+t('serverPick'))+nav()}}
function showServers(s,title,poster,animeId,number){document.getElementById('app').innerHTML=top()+`<section class="section"><h2>${t('serverPick')}</h2><div class="server-list">${s.map((x,i)=>`<button class="server" onclick="openPlayer('${esc(x.url||x.src)}','${esc(title)}','${esc(poster)}','${esc(animeId)}','${esc(number)}')">${esc(x.name||x.server||'Server '+(i+1))}<span>▶</span></button>`).join('')}</div></section>`+nav()}
function openPlayer(url,title,poster,animeId,number){const u=String(url||'');document.getElementById('app').innerHTML=top()+`<section class="player-page"><button class="back" onclick="detail('${esc(animeId)}')">← ${t('back')}</button><div class="player"><video id="video" controls playsinline poster="${esc(poster||'')}" src="${esc(u)}"></video><div class="player-fallback"><b>${t('playing')}</b><p>${esc(title)} • Episode ${esc(number)}</p><a class="cta" href="${esc(u)}" target="_blank" rel="noopener">Open stream</a></div></div><h2>${esc(title)}</h2><p>${t('playing')} • Episode ${esc(number)}</p></section>`+nav();const v=document.getElementById('video');if(v){v.addEventListener('timeupdate',()=>saveProgress(animeId,number,v.currentTime,v.duration,title,poster));v.addEventListener('ended',()=>{const p=getProgress()[animeId];if(p)saveProgress(animeId,number,v.duration,v.duration,title,poster)});v.play().catch(()=>{})}}
async function library(){const fav=getFav(),prog=Object.values(getProgress()).sort((a,b)=>b.updated-a.updated);window._items=fav;return `${top()}${prog.length?`<section class="section"><h2>${t('continue')}</h2><div class="continue">${prog.map(x=>`<div class="cont" onclick="detail('${esc(x.id)}')"><img src="${esc(x.poster||'')}" alt=""><div><b>${esc(x.title)}</b><small>Episode ${esc(x.episode)}</small><div class="bar"><i style="width:${x.duration?Math.min(100,x.time/x.duration*100):0}%"></i></div></div></div>`).join('')}</div></section>`:''}<section class="section"><h2>${t('favorites')} (${fav.length})</h2>${grid(fav)}</section>${nav()}`}
function serverForm(){return `<section class="section settings"><h2>${t('settings')}</h2><label>${t('server')}</label><input id="server" class="search" value="${esc(API)}"><button class="cta" onclick="saveServer()">${t('save')}</button><p class="hint">API URL validation and a 15-second request timeout are enabled.</p></section>`}
async function more(){return `${top()}${serverForm()}<section class="section settings"><h2>${t('language')}</h2><div class="lang"><button onclick="setLang('ku')">کوردی سۆرانی</button><button onclick="setLang('en')">English</button><button onclick="setLang('ar')">العربية</button></div></section><section class="section settings"><h2>About</h2><p class="hint">Kurd Anime • local favorites • continue watching • responsive video player.</p></section>${nav()}`}
async function movies(){let items=[];try{items=normalizeList(await first(['/movies','/anime/movies','/anime/filter?format=MOVIE']))}catch(e){try{items=normalizeList(await api('/gogoanime/anime-movies?page=1'))}catch(_){}}window._items=items;return `${top()}<section class="section"><h2>${t('movies')}</h2>${items.length?grid(items):state(t('offline'),false)}</section>${nav()}`}
function saveServer(){let v=document.getElementById('server')?.value.trim();try{const u=new URL(v);if(!/^https?:$/.test(u.protocol))throw 0;API=v.replace(/\/$/,'');localStorage.apiBase=API;render()}catch(e){alert('Invalid server URL')}}
async function go(p){page=p;render()}
function setLang(x){lang=x;localStorage.lang=x;render()}
async function render(){document.documentElement.dir=lang==='en'?'ltr':'rtl';document.documentElement.lang=lang;const root=document.getElementById('app');root.innerHTML=`<div class="loading"><div class="spinner"></div>${t('loading')}</div>`;try{root.innerHTML=await({home,anime,movies,library,more}[page]||home)()}catch(e){root.innerHTML=top()+state(e.message==='API_NOT_CONFIGURED'?t('offline'):t('offline'))+nav()}}
render();
